import ExcelJS from "exceljs";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import { format } from "date-fns";
import {
  AuditBundle,
  AuditRecordType,
  RECORD_TYPE_LABELS,
  STANDARD_CLAUSES,
} from "@/hooks/useAuditExportBundle";

// ---------- helpers ----------

function slug(s: string): string {
  return (s || "org").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40) || "org";
}

function stamp(bundle: AuditBundle, kind: string, ext: string): string {
  return `JobLineAudit_${slug(bundle.meta.organization_name)}_${bundle.meta.month}_${kind}.${ext}`;
}

function rowsToCsv(rows: any[]): string {
  if (!rows || rows.length === 0) return "";
  const headers = Object.keys(rows[0]);
  const escape = (v: any) => {
    if (v == null) return "";
    const s = typeof v === "object" ? JSON.stringify(v) : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  return [headers.join(","), ...rows.map((r) => headers.map((h) => escape(r[h])).join(","))].join("\n");
}

// ---------- Excel (multi-sheet) ----------

export async function exportAuditBundleToExcel(bundle: AuditBundle): Promise<void> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "JobLine AI";
  wb.created = new Date();

  // Cover sheet
  const cover = wb.addWorksheet("Audit Cover");
  cover.columns = [{ width: 28 }, { width: 60 }];
  const std = STANDARD_CLAUSES[bundle.meta.standard];
  const coverRows: [string, string][] = [
    ["Report", "JobLine.ai Audit Evidence Bundle"],
    ["Organization", bundle.meta.organization_name],
    ["Period", `${bundle.meta.date_from} → ${bundle.meta.date_to} (${bundle.meta.month})`],
    ["Standard", std.label],
    ["Record types", bundle.meta.record_types.map((t) => RECORD_TYPE_LABELS[t]).join(", ")],
    ["Generated at", bundle.meta.generated_at],
    ["Generated by", bundle.meta.generated_by],
    ["", ""],
    ["Clause cross-reference", ""],
    ...std.clauses.map(({ code, topic }) => [code, topic] as [string, string]),
  ];
  coverRows.forEach((r, i) => {
    cover.addRow(r);
    if (i === 0 || r[0] === "Clause cross-reference") cover.lastRow!.font = { bold: true };
  });

  // One sheet per record type
  for (const type of bundle.meta.record_types) {
    const rows = bundle.data[type] || [];
    const sheet = wb.addWorksheet(RECORD_TYPE_LABELS[type].slice(0, 31));
    if (rows.length === 0) {
      sheet.addRow(["No records in selected period."]);
      continue;
    }
    const headers = Object.keys(rows[0]);
    sheet.columns = headers.map((h) => ({ header: h, key: h, width: Math.min(40, Math.max(14, h.length + 2)) }));
    sheet.getRow(1).font = { bold: true };
    sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE0E0E0" } };
    rows.forEach((r) => {
      const out: any = {};
      headers.forEach((h) => {
        const v = (r as any)[h];
        out[h] = v && typeof v === "object" ? JSON.stringify(v) : v ?? "";
      });
      sheet.addRow(out);
    });
  }

  const buf = await wb.xlsx.writeBuffer();
  saveAs(new Blob([buf], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), stamp(bundle, "bundle", "xlsx"));
}

// ---------- CSV zip (one CSV per record type) ----------

export async function exportAuditBundleToCSVZip(bundle: AuditBundle): Promise<void> {
  const zip = new JSZip();
  const folder = zip.folder(`JobLineAudit_${slug(bundle.meta.organization_name)}_${bundle.meta.month}`)!;
  folder.file(
    "README.txt",
    `JobLine.ai audit evidence bundle\nOrganization: ${bundle.meta.organization_name}\nPeriod: ${bundle.meta.date_from} → ${bundle.meta.date_to}\nStandard: ${STANDARD_CLAUSES[bundle.meta.standard].label}\nGenerated: ${bundle.meta.generated_at} by ${bundle.meta.generated_by}\n`
  );
  for (const type of bundle.meta.record_types) {
    folder.file(`${type}.csv`, rowsToCsv(bundle.data[type] || []) || "no records");
  }
  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, stamp(bundle, "bundle", "zip"));
}

// ---------- QuickBooks-style CSV (work orders only) ----------

export function exportAuditBundleToQuickBooksCSV(bundle: AuditBundle): void {
  const wos = bundle.data.work_orders || [];
  const rows = wos.map((wo: any) => ({
    Date: wo.completed_at ? format(new Date(wo.completed_at), "MM/dd/yyyy") : format(new Date(wo.created_at), "MM/dd/yyyy"),
    "Invoice No": wo.work_order || wo.id.slice(0, 8),
    Customer: wo.title || "",
    Item: wo.part_number || "",
    Quantity: wo.quantity || 0,
    Memo: `Status: ${wo.status} | Priority: ${wo.priority}`,
  }));
  const csv = rowsToCsv(rows);
  saveAs(new Blob([csv], { type: "text/csv;charset=utf-8" }), stamp(bundle, "quickbooks", "csv"));
}

// ---------- JSON ----------

export function exportAuditBundleToJSON(bundle: AuditBundle): void {
  saveAs(
    new Blob([JSON.stringify(bundle, null, 2)], { type: "application/json" }),
    stamp(bundle, "bundle", "json")
  );
}

// ---------- PDF (cover + per-type summary table) ----------

export function exportAuditBundleToPDF(bundle: AuditBundle): void {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const std = STANDARD_CLAUSES[bundle.meta.standard];
  let y = 56;
  const line = (t: string, size = 11, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(t, 56, y);
    y += size + 6;
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("JobLine.ai Audit Evidence", 56, y);
  y += 28;
  line(`Organization: ${bundle.meta.organization_name}`, 12, true);
  line(`Period: ${bundle.meta.date_from} → ${bundle.meta.date_to} (${bundle.meta.month})`);
  line(`Standard: ${std.label}`);
  line(`Generated: ${bundle.meta.generated_at}`);
  line(`Generated by: ${bundle.meta.generated_by}`);
  y += 8;
  line("Record counts", 13, true);
  for (const t of bundle.meta.record_types) {
    line(`  ${RECORD_TYPE_LABELS[t]}: ${(bundle.data[t] || []).length}`);
  }
  y += 8;
  line("Clause cross-reference", 13, true);
  for (const c of std.clauses) line(`  ${c.code} — ${c.topic}`, 10);

  doc.save(stamp(bundle, "summary", "pdf"));
}

// ---------- Print HTML ----------

export function printAuditBundleHTML(bundle: AuditBundle): void {
  const std = STANDARD_CLAUSES[bundle.meta.standard];
  const esc = (s: any) => String(s ?? "").replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]!));
  const tables = bundle.meta.record_types
    .map((t) => {
      const rows = bundle.data[t] || [];
      if (rows.length === 0) return `<h2>${RECORD_TYPE_LABELS[t]}</h2><p><em>No records.</em></p>`;
      const headers = Object.keys(rows[0]);
      const head = headers.map((h) => `<th>${esc(h)}</th>`).join("");
      const body = rows
        .map((r: any) => `<tr>${headers.map((h) => `<td>${esc(r[h] && typeof r[h] === "object" ? JSON.stringify(r[h]) : r[h])}</td>`).join("")}</tr>`)
        .join("");
      return `<h2>${RECORD_TYPE_LABELS[t]} (${rows.length})</h2><table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
    })
    .join("");

  const html = `<!doctype html><html><head><title>JobLine Audit — ${esc(bundle.meta.organization_name)} — ${esc(bundle.meta.month)}</title>
<style>body{font-family:system-ui,sans-serif;padding:24px;color:#111}h1{margin:0 0 4px}h2{margin-top:28px;border-bottom:1px solid #ddd;padding-bottom:4px}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border:1px solid #ccc;padding:4px 6px;text-align:left;vertical-align:top}th{background:#f3f4f6}.meta{color:#555;margin-bottom:18px}@media print{h2{page-break-before:always}h1+.meta+*{page-break-before:auto}}</style>
</head><body>
<h1>JobLine.ai Audit Evidence</h1>
<div class="meta"><strong>${esc(bundle.meta.organization_name)}</strong> · ${esc(bundle.meta.date_from)} → ${esc(bundle.meta.date_to)} · ${esc(std.label)} · generated ${esc(bundle.meta.generated_at)} by ${esc(bundle.meta.generated_by)}</div>
${tables}
</body></html>`;
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
}
