export interface Manufacturing100Honoree {
  id: string;
  slug: string | null;
  nominee_name: string;
  nominee_company: string | null;
  nominee_role: string | null;
  nominee_linkedin: string | null;
  nominee_website: string | null;
  category: string;
  display_blurb: string;
  reason: string | null;
  evidence_links: string[];
  rank: number | null;
  previous_rank: number | null;
  rank_movement: string | null;
  score_total: number | null;
  edition: string | null;
  published_at: string;
}

export const EDITORIAL_MANUFACTURING_100_HONOREES: Manufacturing100Honoree[] = [
  {
    "id": "670ffdf9-7604-4148-bffc-11da103a5a1d",
    "slug": "titan-gilroy",
    "nominee_name": "Titan Gilroy",
    "nominee_company": "Titans of CNC",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/titanamericanbuilt/",
    "nominee_website": "https://www.titansofcnc.com",
    "category": "CNC and CAM Leaders",
    "display_blurb": "The most visible advocate for CNC machining as a craft — and the operator behind one of the largest free CNC training libraries online.",
    "reason": "Public face of modern CNC education; Titans of CNC Academy has trained tens of thousands of operators and programmers for free.",
    "evidence_links": [],
    "rank": 1,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 93,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "3ea6875c-af57-47ef-a05c-9a967605f47d",
    "slug": "jensen-huang",
    "nominee_name": "Jensen Huang",
    "nominee_company": "NVIDIA",
    "nominee_role": "Founder & CEO",
    "nominee_linkedin": "https://www.linkedin.com/in/jenhsunhuang/",
    "nominee_website": "https://www.nvidia.com",
    "category": "Industry Catalysts",
    "display_blurb": "NVIDIA compute is the substrate beneath modern CAM optimization, machine vision QA, and shop-floor AI assistants.",
    "reason": "NVIDIA compute is the substrate beneath modern CAM optimization, generative design, machine vision QA, robotic perception, and shop-floor AI assistants.",
    "evidence_links": [],
    "rank": 2,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 92,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "2c2f8b9b-52c0-4d66-8b75-26f7b0d6e5e9",
    "slug": "john-saunders",
    "nominee_name": "John Saunders",
    "nominee_company": "NYC CNC / Saunders Machine Works",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/johnksaunders/",
    "nominee_website": "https://www.nyccnc.com",
    "category": "CNC and CAM Leaders",
    "display_blurb": "Runs a real precision shop in parallel with one of the most-watched practitioner education channels in CNC.",
    "reason": "Pairs a working precision shop with an education channel that has taught a generation of small-shop owners how to run real production work.",
    "evidence_links": [],
    "rank": 3,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 91,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "806eb007-a960-4ed8-a3e5-2335ff8e7cb4",
    "slug": "elon-musk",
    "nominee_name": "Elon Musk",
    "nominee_company": "Tesla, SpaceX",
    "nominee_role": "CEO",
    "nominee_linkedin": null,
    "nominee_website": "https://www.tesla.com",
    "category": "Industry Catalysts",
    "display_blurb": "Pushed vertical integration and high-rate manufacturing — EVs, cells, and orbital-class rockets — past what the industry called impossible.",
    "reason": "Pushed vertical integration and high-rate manufacturing of EVs, batteries, and orbital-class rockets to a scale and cadence the industry treated as impossible a decade ago.",
    "evidence_links": [],
    "rank": 4,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 87,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "a348330d-70c7-441b-ad78-80a5f778d174",
    "slug": "lisa-su",
    "nominee_name": "Lisa Su",
    "nominee_company": "AMD",
    "nominee_role": "Chair & CEO",
    "nominee_linkedin": "https://www.linkedin.com/in/lisa-su-9105132a/",
    "nominee_website": "https://www.amd.com",
    "category": "Industry Catalysts",
    "display_blurb": "Restructured AMD into a leading-edge silicon and AI-accelerator manufacturer competing at the frontier of the foundry process node.",
    "reason": "Restructured AMD into a leading-edge semiconductor and AI accelerator manufacturer; advocate for US semiconductor manufacturing capacity.",
    "evidence_links": [],
    "rank": 5,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 85,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "25ce02a7-957c-43a6-9062-dcbf23762d3d",
    "slug": "marc-lecuyer",
    "nominee_name": "Marc Lecuyer",
    "nominee_company": "Edge Precision",
    "nominee_role": "Founder",
    "nominee_linkedin": null,
    "nominee_website": "https://www.edgeprecision.com",
    "category": "CNC and CAM Leaders",
    "display_blurb": "Aerospace multi-axis authority known for hard-earned technical depth on tooling, work-holding, and turn-mill strategy.",
    "reason": "Multi-axis aerospace machining authority; widely respected technical voice on tooling, work-holding, and turn-mill strategy.",
    "evidence_links": [],
    "rank": 6,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 85,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "6b4ca00a-28b3-4d4c-a28b-92757b46e50d",
    "slug": "jon-hirschtick",
    "nominee_name": "Jon Hirschtick",
    "nominee_company": "Onshape (PTC) / SolidWorks co-founder",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/jonhirschtick/",
    "nominee_website": null,
    "category": "Manufacturing Software Builders",
    "display_blurb": "Co-founded SolidWorks, then built Onshape — two of the most consequential shifts in how design data reaches the shop floor.",
    "reason": "Co-founder of SolidWorks and founder of Onshape; foundational influence on modern CAD and the move to cloud-native engineering software.",
    "evidence_links": [],
    "rank": 7,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 83,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "88115e06-749a-4d5e-83f5-998b01608c26",
    "slug": "mike-rowe",
    "nominee_name": "Mike Rowe",
    "nominee_company": "mikeroweWORKS Foundation",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/mikerowe/",
    "nominee_website": "https://www.mikeroweworks.org",
    "category": "Manufacturing Educators",
    "display_blurb": "Built the most visible national platform advocating for skilled trades — and funded thousands of trades scholarships through mikeroweWORKS.",
    "reason": "Decade-plus advocate for skilled trades and manufacturing careers; the mikeroweWORKS Foundation has funded thousands of trades scholarships.",
    "evidence_links": [],
    "rank": 8,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 83,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "07bb113c-fcf1-44b5-8f96-559769eae689",
    "slug": "morris-chang",
    "nominee_name": "Morris Chang",
    "nominee_company": "TSMC",
    "nominee_role": "Founder",
    "nominee_linkedin": null,
    "nominee_website": "https://www.tsmc.com",
    "category": "Legacy Builders",
    "display_blurb": "Founded TSMC and invented the pure-play foundry model that underpins essentially all modern semiconductor manufacturing.",
    "reason": "Founded TSMC and invented the pure-play foundry model that underwrites essentially all modern semiconductor manufacturing.",
    "evidence_links": [],
    "rank": 9,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 83,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "e57070d3-ec27-4baa-8933-d9e61419d5ad",
    "slug": "marc-raibert",
    "nominee_name": "Marc Raibert",
    "nominee_company": "Boston Dynamics / The AI Institute",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/marc-raibert-90090b6/",
    "nominee_website": "https://theaiinstitute.com",
    "category": "Automation and Robotics Leaders",
    "display_blurb": "Defined the field of dynamic, mobile robotics now reaching inspection, material handling, and shop-floor logistics.",
    "reason": "Founded Boston Dynamics; defined the modern field of dynamic, mobile robotics now being deployed for inspection, material handling, and shop-floor logistics.",
    "evidence_links": [],
    "rank": 10,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 82,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "4524dbe1-50ed-4f28-b2b7-33061f593ced",
    "slug": "rodney-brooks",
    "nominee_name": "Rodney Brooks",
    "nominee_company": "Robust.AI / iRobot / Rethink Robotics",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/rodney-brooks-1a273a/",
    "nominee_website": "https://www.rodneybrooks.com",
    "category": "Automation and Robotics Leaders",
    "display_blurb": "Founder of iRobot and Rethink Robotics, and a candid technical voice on what factory automation can and cannot really do.",
    "reason": "Founder of iRobot and Rethink Robotics; long-running, candid technical voice on what factory automation actually can and cannot do.",
    "evidence_links": [],
    "rank": 11,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 81,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "6e4afe40-13fc-4129-beb3-d4d1ae9ea654",
    "slug": "jacob-harpaz",
    "nominee_name": "Jacob Harpaz",
    "nominee_company": "IMC Group / Iscar",
    "nominee_role": "Chairman",
    "nominee_linkedin": null,
    "nominee_website": "https://www.iscar.com",
    "category": "Tooling and Metrology Leaders",
    "display_blurb": "Decades-long influence on cutting-tool design and machinist-centered productivity tooling.",
    "reason": "Decades-long influence on global cutting-tool design, productivity tooling strategy, and machinist-centered tool development.",
    "evidence_links": [],
    "rank": 12,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 79,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "4845fcf7-acf6-434b-993b-965b017916eb",
    "slug": "melonee-wise",
    "nominee_name": "Melonee Wise",
    "nominee_company": "Agility Robotics",
    "nominee_role": "CTO",
    "nominee_linkedin": "https://www.linkedin.com/in/meloneewise/",
    "nominee_website": "https://agilityrobotics.com",
    "category": "Automation and Robotics Leaders",
    "display_blurb": "Pioneer of practical mobile-manipulation robotics shipping into real warehouses and factories.",
    "reason": "Pioneer of practical mobile manipulation robotics (Willow Garage, Fetch Robotics, Agility) deployed in real warehouses and factories.",
    "evidence_links": [],
    "rank": 13,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 79,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "ba78ed26-d470-458e-aab4-4259f67df5ef",
    "slug": "jay-timmons",
    "nominee_name": "Jay Timmons",
    "nominee_company": "National Association of Manufacturers",
    "nominee_role": "President & CEO",
    "nominee_linkedin": "https://www.linkedin.com/in/jaytimmons/",
    "nominee_website": "https://www.nam.org",
    "category": "Workforce Development Leaders",
    "display_blurb": "Leads NAM's policy and workforce agenda — a consistent national voice for the manufacturing pipeline.",
    "reason": "Leads NAM's policy and workforce agenda; consistent advocate for the manufacturing workforce pipeline at the federal level.",
    "evidence_links": [],
    "rank": 14,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 78,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "f383b91d-3125-4498-a465-77f484b84baf",
    "slug": "carolyn-lee",
    "nominee_name": "Carolyn Lee",
    "nominee_company": "The Manufacturing Institute",
    "nominee_role": "President",
    "nominee_linkedin": "https://www.linkedin.com/in/carolyn-lee-9b69a210/",
    "nominee_website": "https://www.themanufacturinginstitute.org",
    "category": "Workforce Development Leaders",
    "display_blurb": "Built and scaled the modern manufacturing workforce pipeline through Heroes MAKE America, Women MAKE America, and Creators Wanted.",
    "reason": "Runs the workforce development arm of NAM; built and scaled programs (Heroes MAKE America, Women MAKE America, Creators Wanted) feeding the manufacturing pipeline.",
    "evidence_links": [],
    "rank": 15,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 77,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "699b6b2c-ad82-4706-ab1a-852ef1494362",
    "slug": "jeff-bezos",
    "nominee_name": "Jeff Bezos",
    "nominee_company": "Blue Origin / Amazon",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/jeffrey-bezos/",
    "nominee_website": "https://www.blueorigin.com",
    "category": "Industry Catalysts",
    "display_blurb": "Built two operating systems for physical goods: Amazon's global fulfillment supply chain and Blue Origin's in-house rocket manufacturing program.",
    "reason": "Founder of Blue Origin (in-house rocket manufacturing) and architect of the modern logistics and fulfillment supply chain that reshaped how physical goods move at scale.",
    "evidence_links": [],
    "rank": 16,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 77,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "3e9d4668-39c4-4471-8a31-381ba8827ba2",
    "slug": "jeremy-bout",
    "nominee_name": "Jeremy Bout",
    "nominee_company": "Edge Factor",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/jeremybout/",
    "nominee_website": "https://www.edgefactor.com",
    "category": "Manufacturing Educators",
    "display_blurb": "Tells the story of modern manufacturing in classrooms — Edge Factor content reaches thousands of schools every year.",
    "reason": "Produces classroom-ready manufacturing storytelling used in thousands of schools to bring careers in the trades to students.",
    "evidence_links": [],
    "rank": 17,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 77,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "251c1efd-357f-4ab3-9544-7d970f213202",
    "slug": "pat-gelsinger",
    "nominee_name": "Pat Gelsinger",
    "nominee_company": "Intel (former CEO)",
    "nominee_role": "Semiconductor leader",
    "nominee_linkedin": "https://www.linkedin.com/in/patgelsinger/",
    "nominee_website": null,
    "category": "Industry Catalysts",
    "display_blurb": "Drove the IDM 2.0 push to rebuild leading-edge semiconductor fabrication in the United States.",
    "reason": "Led the IDM 2.0 strategy and a generational push to bring leading-edge semiconductor manufacturing back to US soil under the CHIPS Act.",
    "evidence_links": [],
    "rank": 18,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 77,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "f491f1b3-584d-4b65-aec4-33dc98504066",
    "slug": "carl-bass",
    "nominee_name": "Carl Bass",
    "nominee_company": "Autodesk (former CEO)",
    "nominee_role": "Manufacturing software veteran",
    "nominee_linkedin": "https://www.linkedin.com/in/carlbass/",
    "nominee_website": null,
    "category": "Manufacturing Software Builders",
    "display_blurb": "Reshaped Autodesk around Fusion, generative design, and digital fabrication for the modern shop.",
    "reason": "Reshaped Autodesk around generative design, Fusion, and digital fabrication; ongoing investor in manufacturing tools and robotics.",
    "evidence_links": [],
    "rank": 19,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 76,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "260c835d-0839-452c-b92d-2aa761b8d37b",
    "slug": "karen-bischoff",
    "nominee_name": "Karen Bischoff",
    "nominee_company": "Bischoff Tool & Die",
    "nominee_role": "Owner",
    "nominee_linkedin": null,
    "nominee_website": null,
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Second-generation shop owner and visible advocate for women in precision manufacturing and SMB modernization.",
    "reason": "Second-generation shop owner and visible advocate for women in precision manufacturing and SMB shop modernization.",
    "evidence_links": [],
    "rank": 20,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 76,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "87455fc4-7552-4e5b-a4d6-701bba68fbeb",
    "slug": "mike-payne",
    "nominee_name": "Mike Payne",
    "nominee_company": "PTC / SolidWorks co-founder / SpaceClaim",
    "nominee_role": "CAD pioneer",
    "nominee_linkedin": null,
    "nominee_website": null,
    "category": "Legacy Builders",
    "display_blurb": "Co-founded PTC, SolidWorks, and SpaceClaim — three of the most consequential 3D CAD platforms in mechanical design.",
    "reason": "Co-founder of PTC, SolidWorks, and SpaceClaim — three of the most influential 3D CAD platforms in mechanical design history.",
    "evidence_links": [],
    "rank": 21,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 76,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "4fc3ad0b-21f9-4cd3-91d0-452b0fe7fddd",
    "slug": "ric-fulop",
    "nominee_name": "Ric Fulop",
    "nominee_company": "Desktop Metal",
    "nominee_role": "Founder & CEO",
    "nominee_linkedin": "https://www.linkedin.com/in/ricfulop/",
    "nominee_website": "https://www.desktopmetal.com",
    "category": "Manufacturing Software Builders",
    "display_blurb": "Drove metal additive manufacturing toward real shop-floor production economics, not prototyping demos.",
    "reason": "Pushed metal additive manufacturing toward shop-floor production economics, not just prototyping.",
    "evidence_links": [],
    "rank": 22,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 76,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "2baf1836-1d8e-4b2a-9b0a-9fdda6d95968",
    "slug": "tim-cook",
    "nominee_name": "Tim Cook",
    "nominee_company": "Apple",
    "nominee_role": "CEO",
    "nominee_linkedin": "https://www.linkedin.com/in/tim-cook-7475aa153/",
    "nominee_website": "https://www.apple.com",
    "category": "Industry Catalysts",
    "display_blurb": "Architected the operating model behind one of the most studied supply chains in manufacturing — the benchmark for OEM-supplier discipline.",
    "reason": "Built and operates one of the most studied supply chains in manufacturing history; Apple's operational discipline has set the bar for OEM-supplier collaboration for two decades.",
    "evidence_links": [],
    "rank": 23,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 76,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "7f8ba02b-5df6-409e-8c8b-9d370c3d4344",
    "slug": "bre-pettis",
    "nominee_name": "Bre Pettis",
    "nominee_company": "Bantam Tools",
    "nominee_role": "Founder",
    "nominee_linkedin": "https://www.linkedin.com/in/brepettis/",
    "nominee_website": "https://www.bantamtools.com",
    "category": "Manufacturing Software Builders",
    "display_blurb": "Brought rigid desktop CNC and small-footprint precision tools to educators, prototypers, and small shops.",
    "reason": "Brought desktop CNC and rigid small-footprint precision tools to a generation of educators, prototypers, and small shops.",
    "evidence_links": [],
    "rank": 24,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 75,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "87a68199-8017-4450-92cf-282f94a02f49",
    "slug": "justin-quinn",
    "nominee_name": "Justin Quinn",
    "nominee_company": "Falcon Industries",
    "nominee_role": "President",
    "nominee_linkedin": null,
    "nominee_website": null,
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "SMB precision shop leader and longstanding NTMA voice on workforce, apprenticeships, and small-shop competitiveness.",
    "reason": "SMB precision shop leader and longstanding voice in NTMA on workforce, apprenticeships, and small-shop competitiveness.",
    "evidence_links": [],
    "rank": 25,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 75,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "e0aa38a4-dec1-40f6-a2f2-494355a42a16",
    "slug": "scott-walker",
    "nominee_name": "Scott Walker",
    "nominee_company": "Mitutoyo America",
    "nominee_role": "Metrology leader",
    "nominee_linkedin": null,
    "nominee_website": "https://www.mitutoyoamerica.com",
    "category": "Tooling and Metrology Leaders",
    "display_blurb": "Long-running voice for the metrology profession in North American shops and SMB measurement discipline.",
    "reason": "Long-running voice for the metrology profession in North American shops; advocate for measurement discipline in SMB manufacturing.",
    "evidence_links": [],
    "rank": 26,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 70,
    "edition": "2026",
    "published_at": "2026-06-04T17:14:30.852002+00:00"
  },
  {
    "id": "59cf179e-bfea-43dc-9df8-d7aeea05f105",
    "slug": "paul-ricard",
    "nominee_name": "Paul Ricard",
    "nominee_company": "MachiningCloud / DP Technology / Hexagon Manufacturing Intelligence",
    "nominee_role": "Founder & President, MachiningCloud; Co-founder & President, DP Technology (ESPRIT CAM)",
    "nominee_linkedin": null,
    "nominee_website": "https://espritcam.hexagon.com",
    "category": "Manufacturing Software Builders",
    "display_blurb": "Founder & President of MachiningCloud, the cloud-based tooling data platform revolutionizing how CNC shops access cutting tool information. Previously co-founded DP Technology and built ESPRIT CAM into a global standard for multi-axis CNC programming before its acquisition by Hexagon Manufacturing Intelligence. Has shaped digital manufacturing across two generations — from CAM software to cloud-native tooling intelligence.",
    "reason": "Co-founded DP Technology in 1982 and grew ESPRIT into a category-defining multi-axis CAM platform — edit-free G-code, deep post support, and adoption across mill, turn, mill-turn, Swiss, wire EDM, and additive. DP Technology was acquired by Hexagon Manufacturing Intelligence in 2021.",
    "evidence_links": [
      "https://www.amtonline.org/article/la-bonne-vie-40-years-and-going-strong",
      "https://espritcam.hexagon.com/webinar/get-to-know-dp-technology-in-a-webinar-hosted-by-co-founder-paul-ricard",
      "http://espritcam.com/company/about"
    ],
    "rank": 27,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 73,
    "edition": "2026",
    "published_at": "2026-06-04T17:36:17.983793+00:00"
  },
  {
    "id": "a523f35f-d0d8-4077-9d2b-575724d754ba",
    "slug": "dan-frayssinet",
    "nominee_name": "Dan Frayssinet",
    "nominee_company": "DP Technology / Hexagon Manufacturing Intelligence",
    "nominee_role": "Co-founder, DP Technology (ESPRIT CAM)",
    "nominee_linkedin": null,
    "nominee_website": "https://espritcam.hexagon.com",
    "category": "Manufacturing Software Builders",
    "display_blurb": "Co-founder of DP Technology and long-time technical leader behind the ESPRIT CAM platform, now part of Hexagon Manufacturing Intelligence.",
    "reason": "Co-founded DP Technology with Paul Ricard in 1982 and led much of the technical direction behind ESPRIT — knowledge-based machining strategies, true multi-axis simultaneous toolpaths, and edit-free, controller-correct post output trusted by precision shops worldwide.",
    "evidence_links": [
      "https://www.digitalengineering247.com/article/qa-dan-frayssinet",
      "http://espritcam.com/company/about",
      "https://www.americanmachinist.com/cad-and-cam/article/21147613/cam-developer-dp-technology-acquired-hexagon-manufacturing-intelligence"
    ],
    "rank": 28,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 69,
    "edition": "2026",
    "published_at": "2026-06-04T17:36:17.983793+00:00"
  },
  {
    "id": "3c3942d8-8f56-4f11-ab86-ce21f7e62397",
    "slug": "brandon-aymar",
    "nominee_name": "Brandon Aymar",
    "nominee_company": "Aymar Engineering / RevShocks / RevGrips",
    "nominee_role": "Founder & CEO",
    "nominee_linkedin": "https://www.linkedin.com/in/brandon-aymar-a79228a/",
    "nominee_website": "https://www.revshocks.com",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Santee-based engineer-owner building patented bypass shocks and MTB suspension grips fully in-house — the kind of American precision SMB this list exists to surface.",
    "reason": "Owner-operator of a Santee, CA precision shop manufacturing patented off-road and MTB suspension products entirely in-house; granted US Patent 12,472,793 (Nov 2025) for an adjustable bypass shock absorber. Textbook American SMB precision manufacturing.",
    "evidence_links": [
      "https://patentsgazette.uspto.gov/week46/OG/html/1540-3/US12472793-20251118.html",
      "https://www.revshocks.com/pages/about-us",
      "https://bikebiz.com/cyclorise-to-distribute-revgrips-in-uk/"
    ],
    "rank": 29,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 63,
    "edition": "2026",
    "published_at": "2026-06-04T18:01:41.99592+00:00"
  },
  {
    "id": "429d069f-c17c-4fd7-91b2-59694073084a",
    "slug": "nicole-wolter",
    "nominee_name": "Nicole Wolter",
    "nominee_company": "HM Manufacturing (Wauconda, IL)",
    "nominee_role": "President & CEO",
    "nominee_linkedin": null,
    "nominee_website": "https://www.hm-mfg.com/",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "President and CEO of HM Manufacturing, a precision power-transmission components job shop. Manufacturing Institute fellow and one of the most cited SMB manufacturing voices in the U.S.",
    "reason": "Nationally visible SMB precision manufacturing leader and workforce advocate.",
    "evidence_links": [
      "https://www.hm-mfg.com/about",
      "https://www.themanufacturinginstitute.org/"
    ],
    "rank": 30,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 72,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "f965de16-d34f-4b82-b953-ce97f61852af",
    "slug": "aneesa-muthana",
    "nominee_name": "Aneesa Muthana",
    "nominee_company": "Pioneer Service Inc. / M&M Quality Grinding (Addison, IL)",
    "nominee_role": "Co-Owner & CEO",
    "nominee_linkedin": null,
    "nominee_website": "https://www.pioneerservice.com/",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Co-owner and CEO of two Illinois precision machining shops. PMPA leader and frequent national speaker on SMB precision manufacturing and workforce development.",
    "reason": "PMPA leader and nationally visible SMB precision advocate.",
    "evidence_links": [
      "https://www.pioneerservice.com/",
      "https://www.pmpa.org/"
    ],
    "rank": 31,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 70,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "6ee3dd93-e64a-40c2-8678-84a14b44bfb1",
    "slug": "tapani-sisters",
    "nominee_name": "Lori and Traci Tapani",
    "nominee_company": "Wyoming Machine (Stacy, MN)",
    "nominee_role": "Co-Presidents",
    "nominee_linkedin": null,
    "nominee_website": "https://www.wyomingmachine.com/",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Sister co-presidents of Wyoming Machine. Among the longest-running national voices on running a small fabrication shop differently — FMA, Fabricator Podcast, and White House roundtable participants.",
    "reason": "Long-running national SMB fabrication voice.",
    "evidence_links": [
      "https://www.wyomingmachine.com/",
      "https://www.thefabricator.com/"
    ],
    "rank": 32,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 69,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "88895a28-3530-48e8-8ec4-9d2b22b8dc5f",
    "slug": "melissa-ramos",
    "nominee_name": "Melissa Ramos",
    "nominee_company": "M95 Machining",
    "nominee_role": "Owner",
    "nominee_linkedin": null,
    "nominee_website": null,
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "First-generation woman owner of M95 Machining, featured in Modern Machine Shop's \"How I Made It\" series (June 2026). Represents the rising wave of operator-owners building precision shops from the floor up.",
    "reason": "First-gen woman shop owner profiled in Modern Machine Shop.",
    "evidence_links": [
      "https://www.mmsonline.com/"
    ],
    "rank": 33,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 60,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "82976cd3-755e-400e-9054-03f9d0b97e27",
    "slug": "hernan-ricaurte",
    "nominee_name": "Hernan Ricaurte",
    "nominee_company": "Ricaurte Precision Inc. (Southern California)",
    "nominee_role": "President",
    "nominee_linkedin": null,
    "nominee_website": "https://www.ricaurteprecision.com/",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Second-generation owner who quadrupled Ricaurte Precision Inc. Featured on the Capacity Podcast as an immigrant-family precision-manufacturing success story.",
    "reason": "Second-gen owner who quadrupled the shop.",
    "evidence_links": [
      "https://www.ricaurteprecision.com/",
      "https://www.capacitypodcast.com/"
    ],
    "rank": 34,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 63,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "9c50e368-a77e-41e6-9a14-38d73e250237",
    "slug": "rodd-blessey",
    "nominee_name": "Rodd Blessey",
    "nominee_company": "Aldine Metal Products",
    "nominee_role": "President",
    "nominee_linkedin": null,
    "nominee_website": null,
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Third-generation president of Aldine Metal Products, a 35-machine precision metal fabrication shop. Featured on the Capacity Podcast discussing succession and SMB shop scaling.",
    "reason": "Third-gen leader of 35-machine precision fab shop.",
    "evidence_links": [
      "https://www.capacitypodcast.com/"
    ],
    "rank": 35,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 59,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "9b9e1e52-a915-4cbe-98ae-c745de51bb90",
    "slug": "erich-baur",
    "nominee_name": "Erich Baur",
    "nominee_company": "Nordstrand Precision (Colorado Springs, CO)",
    "nominee_role": "Founder",
    "nominee_linkedin": null,
    "nominee_website": "https://nordstrandprecision.com/",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Engineering graduate and Peace Corps alum who built Nordstrand Precision into a ~$20M precision machining shop in Colorado Springs. Model for engineer-founded SMB shops.",
    "reason": "Engineer-founder who built a $20M precision shop.",
    "evidence_links": [
      "https://nordstrandprecision.com/",
      "https://www.coloradomep.org/"
    ],
    "rank": 36,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 62,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "add68236-31de-47d8-979e-568a5dec47b9",
    "slug": "shane-grant",
    "nominee_name": "Shane Grant",
    "nominee_company": "Machining Momentum LLC",
    "nominee_role": "Owner",
    "nominee_linkedin": null,
    "nominee_website": "https://www.machiningmomentum.com/",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Precision shop owner and the creator behind the Machining Momentum content series, helping working machinists improve their craft and run better small shops.",
    "reason": "Shop owner and content creator for working machinists.",
    "evidence_links": [
      "https://www.machiningmomentum.com/"
    ],
    "rank": 37,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 59,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  },
  {
    "id": "8887b3d0-d9c3-4db0-b45d-7d2a7e157eca",
    "slug": "ryan-green",
    "nominee_name": "Ryan Green",
    "nominee_company": "RQC Manufacturing (Liberty Hill, TX)",
    "nominee_role": "Owner-Operator",
    "nominee_linkedin": null,
    "nominee_website": "https://www.rqcmanufacturing.com/",
    "category": "Small and Mid-Size Shop Leaders",
    "display_blurb": "Owner-operator of RQC Manufacturing with 16+ years hands-on precision CNC experience. Representative of the Austin-area boom of operator-owned precision shops.",
    "reason": "Austin-area operator-owner of precision CNC shop.",
    "evidence_links": [
      "https://www.rqcmanufacturing.com/"
    ],
    "rank": 38,
    "previous_rank": null,
    "rank_movement": "new",
    "score_total": 54,
    "edition": "2026",
    "published_at": "2026-06-04T18:08:10.486057+00:00"
  }
];

export function mergeManufacturing100Honorees(
  liveHonorees: Manufacturing100Honoree[],
): Manufacturing100Honoree[] {
  if (liveHonorees.length === 0) {
    return EDITORIAL_MANUFACTURING_100_HONOREES;
  }

  const bySlug = new Map<string, Manufacturing100Honoree>();
  for (const honoree of EDITORIAL_MANUFACTURING_100_HONOREES) {
    if (honoree.slug) bySlug.set(honoree.slug, honoree);
  }
  for (const honoree of liveHonorees) {
    if (honoree.slug) bySlug.set(honoree.slug, honoree);
  }

  return Array.from(bySlug.values()).sort((a, b) => {
    const rankA = a.rank ?? Number.MAX_SAFE_INTEGER;
    const rankB = b.rank ?? Number.MAX_SAFE_INTEGER;
    if (rankA !== rankB) return rankA - rankB;
    return a.nominee_name.localeCompare(b.nominee_name);
  });
}

export function findManufacturing100HonoreeBySlug(
  slug: string | undefined,
  liveHonorees: Manufacturing100Honoree[] = [],
): Manufacturing100Honoree | null {
  if (!slug) return null;
  return (
    liveHonorees.find((honoree) => honoree.slug === slug) ??
    EDITORIAL_MANUFACTURING_100_HONOREES.find((honoree) => honoree.slug === slug) ??
    null
  );
}
