import { ShiftHandoffRecord, StationInfo } from "@/types/handoff";

export const mockStations: StationInfo[] = [
  // CNC Machines
  {
    stationId: "CNC-001",
    name: "Haas VF-2SS",
    workCenter: "WC-MILL-01",
    workCenterType: "CNC Mill",
    currentJob: {
      workOrder: "WO-2024-1547",
      partNumber: "PN-8842-A",
      state: "Part Running",
      operator: "Mike Johnson",
      partsComplete: 45,
      partsRequired: 100,
    },
    condition: {
      coolantLevel: "OK",
      airPressure: "OK",
      chipCondition: "Clear",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
    isActive: true,
  },
  {
    stationId: "CNC-002",
    name: "DMG MORI NLX",
    workCenter: "WC-TURN-01",
    workCenterType: "CNC Lathe",
    currentJob: {
      workOrder: "WO-2024-1552",
      partNumber: "PN-3321-C",
      state: "Setup in Progress",
      operator: "Sarah Chen",
      partsComplete: 0,
      partsRequired: 250,
    },
    condition: {
      coolantLevel: "Low",
      airPressure: "OK",
      chipCondition: "Needs Cleaning",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
    isActive: true,
  },
  // Water Jet
  {
    stationId: "WJ-001",
    name: "Flow Mach 500",
    workCenter: "WC-CUT-01",
    workCenterType: "Water Jet",
    currentJob: {
      workOrder: "WO-2024-1560",
      partNumber: "PN-4455-B",
      state: "Part Running",
      operator: "Carlos Mendez",
      partsComplete: 28,
      partsRequired: 40,
    },
    condition: {
      waterPressure: "OK",
      abrasiveLevel: "OK",
      nozzleCondition: "OK",
      tankLevel: "OK",
    },
    isActive: true,
  },
  // Press Brake
  {
    stationId: "PB-001",
    name: "Trumpf TruBend 5130",
    workCenter: "WC-FORM-01",
    workCenterType: "Press Brake",
    currentJob: {
      workOrder: "WO-2024-1558",
      partNumber: "PN-7712-D",
      state: "First Article in Process",
      operator: "James Wilson",
      partsComplete: 1,
      partsRequired: 85,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
  // TIG Welding
  {
    stationId: "TIG-001",
    name: "TIG Station 1",
    workCenter: "WC-WELD-01",
    workCenterType: "TIG Welding",
    currentJob: {
      workOrder: "WO-2024-1555",
      partNumber: "PN-9923-A",
      state: "Processing",
      operator: "Maria Garcia",
      partsComplete: 15,
      partsRequired: 30,
    },
    condition: {
      gasLevel: "OK",
      wireLevel: "OK",
      tipCondition: "OK",
      groundConnection: "OK",
      ventilationOK: true,
    },
    isActive: true,
  },
  // MIG Welding
  {
    stationId: "MIG-001",
    name: "MIG Station 1",
    workCenter: "WC-WELD-02",
    workCenterType: "MIG Welding",
    currentJob: {
      workOrder: "WO-2024-1561",
      partNumber: "PN-2245-C",
      state: "Waiting on Material",
      operator: "Robert Taylor",
      partsComplete: 8,
      partsRequired: 50,
    },
    condition: {
      gasLevel: "Low",
      wireLevel: "OK",
      tipCondition: "Replace",
      groundConnection: "OK",
      ventilationOK: true,
    },
    isActive: true,
  },
  // Electron Beam Welding
  {
    stationId: "EBW-001",
    name: "Sciaky EB Welder",
    workCenter: "WC-WELD-03",
    workCenterType: "Electron Beam Welding",
    currentJob: {
      workOrder: "WO-2024-1549",
      partNumber: "PN-7756-B",
      state: "Waiting on QA",
      operator: "Tom Williams",
      partsComplete: 12,
      partsRequired: 50,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
  // Punch Press
  {
    stationId: "PP-001",
    name: "Amada EM-2510NT",
    workCenter: "WC-CUT-02",
    workCenterType: "Punch Press",
    currentJob: {
      workOrder: "WO-2024-1545",
      partNumber: "PN-2289-D",
      state: "Machine Down / Issue",
      operator: "Alex Rivera",
      partsComplete: 88,
      partsRequired: 150,
    },
    condition: {
      status: "Issue",
      notes: "Turret alignment issue - maintenance called",
    },
    isActive: true,
  },
  // Hardware Installation
  {
    stationId: "HW-001",
    name: "Hardware Station 1",
    workCenter: "WC-FINISH-01",
    workCenterType: "Hardware Installation",
    currentJob: {
      workOrder: "WO-2024-1553",
      partNumber: "PN-5543-A",
      state: "Processing",
      operator: "Lisa Park",
      partsComplete: 22,
      partsRequired: 75,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
  // Deburr Station
  {
    stationId: "DBR-001",
    name: "Deburr Station 1",
    workCenter: "WC-FINISH-02",
    workCenterType: "Deburr Station",
    currentJob: {
      workOrder: "WO-2024-1556",
      partNumber: "PN-6678-B",
      state: "Processing",
      operator: "Kevin Brown",
      partsComplete: 140,
      partsRequired: 200,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
  // Shipping
  {
    stationId: "SHIP-001",
    name: "Shipping Dock 1",
    workCenter: "WC-SHIP-01",
    workCenterType: "Shipping",
    currentJob: {
      workOrder: "WO-2024-1540",
      partNumber: "MULTI",
      state: "Ready for Pickup",
      operator: "David Lee",
      partsComplete: 3,
      partsRequired: 5,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
  // Incoming Inspection
  {
    stationId: "INC-001",
    name: "Incoming QA",
    workCenter: "WC-QA-01",
    workCenterType: "Incoming Inspection",
    currentJob: {
      workOrder: "WO-2024-1565",
      partNumber: "PN-1122-A",
      state: "Processing",
      operator: "Jennifer Adams",
      partsComplete: 45,
      partsRequired: 100,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
  // Outgoing Inspection
  {
    stationId: "OUT-001",
    name: "Final Inspection",
    workCenter: "WC-QA-02",
    workCenterType: "Outgoing Inspection",
    currentJob: {
      workOrder: "WO-2024-1548",
      partNumber: "PN-3344-C",
      state: "Processing",
      operator: "Michael Chen",
      partsComplete: 67,
      partsRequired: 100,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
  // Tool Crib
  {
    stationId: "TOOL-001",
    name: "Tool Crib",
    workCenter: "WC-TOOL-01",
    workCenterType: "Tool Crib",
    currentJob: {
      workOrder: "TOOL-MGMT",
      partNumber: "N/A",
      state: "Processing",
      operator: "Steve Martin",
      partsComplete: 0,
      partsRequired: 0,
    },
    condition: {
      status: "OK",
    },
    isActive: true,
  },
];

export const mockHandoffRecords: ShiftHandoffRecord[] = [
  {
    recordId: "HO-2024-0547",
    recordVersion: 1,
    date: "2024-01-25",
    shift: "Day",
    workOrder: "WO-2024-1547",
    workCenter: "WC-MILL-01",
    workCenterType: "CNC Mill",
    machineId: "CNC-001",
    part: {
      partNumber: "PN-8842-A",
      revision: "Rev C",
      operationNumber: "OP-20",
    },
    personnel: {
      outgoingOperator: "Mike Johnson",
      incomingOperator: "Dave Wilson",
      supervisor: "Karen Smith",
    },
    jobState: {
      primaryState: "Part Running",
      delayCode: "None",
    },
    machineReadiness: {
      programLoaded: "Yes",
      programVerifiedAgainstSetup: "Yes",
      toolsInstalled: "Yes",
      toolsSetMeasured: "Yes",
      toolListMatchesProgram: "Yes",
      workOffsetsSet: "Yes",
      probingCompleted: "Yes",
      proveOutCompleted: "Yes",
    },
    machineCondition: {
      coolantLevel: "OK",
      airPressure: "OK",
      chipCondition: "Clear",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
    qualityStatus: {
      lastGoodPartTimestamp: "2024-01-25T14:30:00Z",
      partsCompletedThisShift: 45,
      scrapCount: 1,
      reworkCount: 0,
      criticalDimsVerified: true,
      qaNotified: "N/A",
    },
    setupProcess: {
      fixtureInstalled: "Yes",
      clampsBoltsTorqued: "Yes",
      fixtureOrientationVerified: "Yes",
      specialInstructionsFollowed: "Yes",
    },
    materialsStatus: {
      rawMaterialAvailable: true,
      nextMaterialLotReady: true,
      materialIssuesNoted: false,
    },
    handoffSummary: "Machine running smoothly, 55 parts remaining. Tool T4 showing slight wear, monitor closely.",
    signOff: {
      outgoingOperatorName: "Mike Johnson",
      incomingOperatorName: "Dave Wilson",
      supervisorName: "Karen Smith",
      outgoingTime: "2024-01-25T15:00:00Z",
      incomingTime: "2024-01-25T15:05:00Z",
      supervisorTime: "2024-01-25T15:10:00Z",
    },
    createdAt: "2024-01-25T15:00:00Z",
    updatedAt: "2024-01-25T15:10:00Z",
  },
  {
    recordId: "HO-2024-0548",
    recordVersion: 1,
    date: "2024-01-25",
    shift: "Day",
    workOrder: "WO-2024-1555",
    workCenter: "WC-WELD-01",
    workCenterType: "TIG Welding",
    machineId: "TIG-001",
    part: {
      partNumber: "PN-9923-A",
      revision: "Rev A",
      operationNumber: "OP-30",
    },
    personnel: {
      outgoingOperator: "Maria Garcia",
      incomingOperator: "Tony Stark",
    },
    jobState: {
      primaryState: "Processing",
      delayCode: "None",
    },
    equipmentReadiness: {
      equipmentReady: "Yes",
      safetyChecksComplete: "Yes",
      toolsAvailable: "Yes",
      materialsStaged: "Yes",
      workInstructionsAvailable: "Yes",
      ppeVerified: "Yes",
    },
    weldingCondition: {
      gasLevel: "OK",
      wireLevel: "OK",
      tipCondition: "OK",
      groundConnection: "OK",
      ventilationOK: true,
    },
    qualityStatus: {
      lastGoodPartTimestamp: "2024-01-25T14:45:00Z",
      partsCompletedThisShift: 15,
      scrapCount: 0,
      reworkCount: 1,
      criticalDimsVerified: true,
      qaNotified: "N/A",
    },
    setupProcess: {
      fixtureInstalled: "Yes",
      clampsBoltsTorqued: "Yes",
      fixtureOrientationVerified: "Yes",
      specialInstructionsFollowed: "Yes",
    },
    materialsStatus: {
      rawMaterialAvailable: true,
      nextMaterialLotReady: true,
      materialIssuesNoted: false,
    },
    handoffSummary: "Welding going well. One rework on part #12 due to porosity - adjusted gas flow. Check tungsten before continuing.",
    signOff: {
      outgoingOperatorName: "Maria Garcia",
      incomingOperatorName: "Tony Stark",
      outgoingTime: "2024-01-25T15:00:00Z",
      incomingTime: "2024-01-25T15:02:00Z",
    },
    createdAt: "2024-01-25T15:00:00Z",
    updatedAt: "2024-01-25T15:02:00Z",
  },
  {
    recordId: "HO-2024-0549",
    recordVersion: 1,
    date: "2024-01-25",
    shift: "Day",
    workOrder: "WO-2024-1560",
    workCenter: "WC-CUT-01",
    workCenterType: "Water Jet",
    machineId: "WJ-001",
    part: {
      partNumber: "PN-4455-B",
      revision: "Rev B",
      operationNumber: "OP-10",
    },
    personnel: {
      outgoingOperator: "Carlos Mendez",
      incomingOperator: "Ana Rodriguez",
    },
    jobState: {
      primaryState: "Part Running",
      delayCode: "None",
    },
    equipmentReadiness: {
      equipmentReady: "Yes",
      safetyChecksComplete: "Yes",
      toolsAvailable: "Yes",
      materialsStaged: "Yes",
      workInstructionsAvailable: "Yes",
      ppeVerified: "Yes",
    },
    waterJetCondition: {
      waterPressure: "OK",
      abrasiveLevel: "OK",
      nozzleCondition: "OK",
      tankLevel: "OK",
    },
    qualityStatus: {
      lastGoodPartTimestamp: "2024-01-25T14:50:00Z",
      partsCompletedThisShift: 28,
      scrapCount: 0,
      reworkCount: 0,
      criticalDimsVerified: true,
      qaNotified: "N/A",
    },
    setupProcess: {
      fixtureInstalled: "Yes",
      clampsBoltsTorqued: "Yes",
      fixtureOrientationVerified: "Yes",
      specialInstructionsFollowed: "Yes",
    },
    materialsStatus: {
      rawMaterialAvailable: true,
      nextMaterialLotReady: false,
      materialIssuesNoted: false,
      materialNotes: "Next material lot needs to be pulled from warehouse",
    },
    handoffSummary: "Running smoothly. 12 parts remaining. Need to pull next material lot from warehouse before end of swing shift.",
    signOff: {
      outgoingOperatorName: "Carlos Mendez",
      incomingOperatorName: "Ana Rodriguez",
      outgoingTime: "2024-01-25T15:00:00Z",
      incomingTime: "2024-01-25T15:03:00Z",
    },
    createdAt: "2024-01-25T15:00:00Z",
    updatedAt: "2024-01-25T15:03:00Z",
  },
];

export const getCurrentShift = (): "Day" | "Swing" | "Night" => {
  const hour = new Date().getHours();
  if (hour >= 6 && hour < 14) return "Day";
  if (hour >= 14 && hour < 22) return "Swing";
  return "Night";
};
