import { ShiftHandoffRecord, MachineInfo } from "@/types/handoff";

export const mockMachines: MachineInfo[] = [
  {
    machineId: "CNC-001",
    name: "Haas VF-2SS",
    workCenter: "WC-MILL-01",
    currentJob: {
      workOrder: "WO-2024-1547",
      partNumber: "PN-8842-A",
      state: "Part Running",
      operator: "Mike Johnson",
      partsComplete: 45,
      partsRequired: 100,
    },
    condition: {
      coolantLevel: "OK",
      airPressure: "OK",
      chipCondition: "Clear",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
  },
  {
    machineId: "CNC-002",
    name: "DMG MORI NLX",
    workCenter: "WC-TURN-01",
    currentJob: {
      workOrder: "WO-2024-1552",
      partNumber: "PN-3321-C",
      state: "Setup in Progress",
      operator: "Sarah Chen",
      partsComplete: 0,
      partsRequired: 250,
    },
    condition: {
      coolantLevel: "Low",
      airPressure: "OK",
      chipCondition: "Needs Cleaning",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
  },
  {
    machineId: "CNC-003",
    name: "Mazak QTN-350",
    workCenter: "WC-TURN-02",
    currentJob: {
      workOrder: "WO-2024-1549",
      partNumber: "PN-7756-B",
      state: "Waiting on QA",
      operator: "Tom Williams",
      partsComplete: 12,
      partsRequired: 50,
    },
    condition: {
      coolantLevel: "OK",
      airPressure: "OK",
      chipCondition: "Clear",
      wayLube: "Check",
      guardsDoors: "OK",
      activeAlarms: false,
    },
  },
  {
    machineId: "CNC-004",
    name: "Okuma LB3000",
    workCenter: "WC-TURN-03",
    currentJob: {
      workOrder: "WO-2024-1545",
      partNumber: "PN-2289-D",
      state: "Machine Down / Issue",
      operator: "Alex Rivera",
      partsComplete: 88,
      partsRequired: 150,
    },
    condition: {
      coolantLevel: "OK",
      airPressure: "Low",
      chipCondition: "Needs Cleaning",
      wayLube: "OK",
      guardsDoors: "Issue",
      activeAlarms: true,
      alarmNotes: "Spindle overload alarm - E1023",
    },
  },
  {
    machineId: "CNC-005",
    name: "Brother S700X2",
    workCenter: "WC-MILL-02",
    currentJob: {
      workOrder: "WO-2024-1553",
      partNumber: "PN-5543-A",
      state: "First Article in Process",
      operator: "Lisa Park",
      partsComplete: 1,
      partsRequired: 75,
    },
    condition: {
      coolantLevel: "OK",
      airPressure: "OK",
      chipCondition: "Clear",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
  },
];

export const mockHandoffRecords: ShiftHandoffRecord[] = [
  {
    recordId: "HO-2024-0547",
    recordVersion: 1,
    date: "2024-01-25",
    shift: "Day",
    workOrder: "WO-2024-1547",
    workCenter: "WC-MILL-01",
    machineId: "CNC-001",
    part: {
      partNumber: "PN-8842-A",
      revision: "Rev C",
      operationNumber: "OP-20",
    },
    personnel: {
      outgoingOperator: "Mike Johnson",
      incomingOperator: "Dave Wilson",
      supervisor: "Karen Smith",
    },
    jobState: {
      primaryState: "Part Running",
      delayCode: "None",
    },
    machineReadiness: {
      programLoaded: "Yes",
      programVerifiedAgainstSetup: "Yes",
      toolsInstalled: "Yes",
      toolsSetMeasured: "Yes",
      toolListMatchesProgram: "Yes",
      workOffsetsSet: "Yes",
      probingCompleted: "Yes",
      proveOutCompleted: "Yes",
    },
    machineCondition: {
      coolantLevel: "OK",
      airPressure: "OK",
      chipCondition: "Clear",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
    qualityStatus: {
      lastGoodPartTimestamp: "2024-01-25T14:30:00Z",
      partsCompletedThisShift: 45,
      scrapCount: 1,
      reworkCount: 0,
      criticalDimsVerified: true,
      qaNotified: "N/A",
    },
    setupProcess: {
      fixtureInstalled: "Yes",
      clampsBoltsTorqued: "Yes",
      fixtureOrientationVerified: "Yes",
      specialInstructionsFollowed: "Yes",
    },
    materialsStatus: {
      rawMaterialAvailable: true,
      nextMaterialLotReady: true,
      materialIssuesNoted: false,
    },
    handoffSummary: "Machine running smoothly, 55 parts remaining. Tool T4 showing slight wear, monitor closely.",
    signOff: {
      outgoingOperatorName: "Mike Johnson",
      incomingOperatorName: "Dave Wilson",
      supervisorName: "Karen Smith",
      outgoingTime: "2024-01-25T15:00:00Z",
      incomingTime: "2024-01-25T15:05:00Z",
      supervisorTime: "2024-01-25T15:10:00Z",
    },
    createdAt: "2024-01-25T15:00:00Z",
    updatedAt: "2024-01-25T15:10:00Z",
  },
  {
    recordId: "HO-2024-0546",
    recordVersion: 1,
    date: "2024-01-25",
    shift: "Day",
    workOrder: "WO-2024-1552",
    workCenter: "WC-TURN-01",
    machineId: "CNC-002",
    part: {
      partNumber: "PN-3321-C",
      revision: "Rev A",
      operationNumber: "OP-10",
    },
    personnel: {
      outgoingOperator: "Sarah Chen",
      incomingOperator: "Bob Martinez",
    },
    jobState: {
      primaryState: "Setup in Progress",
      reason: "New job setup, waiting on fixture verification",
      delayCode: "Setup",
    },
    machineReadiness: {
      programLoaded: "Yes",
      programVerifiedAgainstSetup: "No",
      toolsInstalled: "Yes",
      toolsSetMeasured: "No",
      toolListMatchesProgram: "Yes",
      workOffsetsSet: "No",
      probingCompleted: "No",
      proveOutCompleted: "No",
      notes: "Tool lengths need verification before first cut",
    },
    machineCondition: {
      coolantLevel: "Low",
      airPressure: "OK",
      chipCondition: "Needs Cleaning",
      wayLube: "OK",
      guardsDoors: "OK",
      activeAlarms: false,
    },
    qualityStatus: {
      lastGoodPartTimestamp: "",
      partsCompletedThisShift: 0,
      scrapCount: 0,
      reworkCount: 0,
      criticalDimsVerified: false,
      qaNotified: "N/A",
    },
    setupProcess: {
      fixtureInstalled: "Partial",
      clampsBoltsTorqued: "No",
      fixtureOrientationVerified: "No",
      specialInstructionsFollowed: "N/A",
      processNotesForNextShift: "Complete fixture install and run dry cycle before first cut",
    },
    materialsStatus: {
      rawMaterialAvailable: true,
      nextMaterialLotReady: false,
      materialIssuesNoted: false,
      materialNotes: "First lot staged at machine",
    },
    handoffSummary: "Setup 60% complete. Finish fixture install, verify tool lengths, run dry cycle before cutting.",
    signOff: {
      outgoingOperatorName: "Sarah Chen",
      incomingOperatorName: "Bob Martinez",
      outgoingTime: "2024-01-25T15:00:00Z",
      incomingTime: "2024-01-25T15:03:00Z",
    },
    createdAt: "2024-01-25T15:00:00Z",
    updatedAt: "2024-01-25T15:03:00Z",
  },
];

export const getCurrentShift = (): "Day" | "Swing" | "Night" => {
  const hour = new Date().getHours();
  if (hour >= 6 && hour < 14) return "Day";
  if (hour >= 14 && hour < 22) return "Swing";
  return "Night";
};
