/**
 * San Diego County flyer drop — MASTER ROUTE DATA
 * Source: jobline_route_MASTER_FINAL.pdf (190+ verified businesses, 22 zones)
 *
 * NOT exported via /public. Admin/flyer_worker access only.
 *
 * isPriority  — ★ marker in PDF (8–10 flyers, prime target)
 * isFirearms  — ■ firearms/gunsmith context
 * isOffRoad   — ■ off-road/racing context
 * isAerospace — ✈ aerospace context
 */

export interface DropStop {
  key: string;
  name: string;
  address: string;
  city: string;
  zip: string;
  phone?: string;
  hours?: string;
  notes?: string;
  isPriority: boolean;
  isFirearms: boolean;
  isOffRoad: boolean;
  isAerospace: boolean;
}

export const ZONE_STOPS: Record<number, DropStop[]> = {

  // ─── Zone 1 — Wheatlands / Abraham Way, Santee ───────────────────────────
  1: [
    {
      key: "kinetic_cnc_santee",
      name: "Kinetic CNC",
      address: "9270 Abraham Way",
      city: "Santee",
      zip: "92071",
      notes: "CNC precision shop, strong fit",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "cim_santee",
      name: "CIM (Custom Industrial Machining)",
      address: "9240 Abraham Way",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "aluminess",
      name: "Aluminess Products",
      address: "9270 Wheatlands Ave",
      city: "Santee",
      zip: "92071",
      notes: "Aluminum truck accessories, fabrication",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "alumicraft",
      name: "Alumicraft",
      address: "9250 Wheatlands Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "ls_precision",
      name: "L&S Precision",
      address: "9290 Abraham Way",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "aymar_industries",
      name: "Aymar Industries",
      address: "9230 Abraham Way",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "eastwood_machine",
      name: "Eastwood Machine",
      address: "9260 Wheatlands Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "quality_controlled_mfg",
      name: "Quality Controlled Mfg",
      address: "9275 Abraham Way",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "mathy_machine",
      name: "Mathy Machine",
      address: "9285 Abraham Way",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "vortex_engineering",
      name: "Vortex Engineering",
      address: "9295 Wheatlands Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "wheatlands_cluster",
      name: "Wheatlands Multi-Tenant Cluster",
      address: "9200–9300 Wheatlands Ave",
      city: "Santee",
      zip: "92071",
      notes: "Multiple small shops — leave stack at front office",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 2 — Prospect / Buena Vista / Kenney, Santee ────────────────────
  2: [
    {
      key: "ralls_precision",
      name: "Ralls Precision",
      address: "8965 Prospect Ave",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "adiem_engineering",
      name: "ADIEM Engineering",
      address: "8940 Buena Vista Ave",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "edge_engineering",
      name: "Edge Engineering",
      address: "8960 Buena Vista Ave",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "performant_mfg",
      name: "Performant Manufacturing",
      address: "8980 Buena Vista Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "conns_machining",
      name: "Conn's Machining",
      address: "9020 Prospect Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "cm_mfg",
      name: "C&M Manufacturing",
      address: "8950 Kenney St",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "creative_metal",
      name: "Creative Metal",
      address: "8970 Kenney St",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "bti_cnc",
      name: "BTI CNC",
      address: "8990 Kenney St",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "bs_designs",
      name: "BS Designs",
      address: "9010 Prospect Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "industrial_metal_processing",
      name: "Industrial Metal Processing",
      address: "9030 Buena Vista Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "the_dyno_shop",
      name: "The Dyno Shop",
      address: "9040 Prospect Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "garys_auto_santee",
      name: "Gary's Auto",
      address: "9050 Kenney St",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 3 — Cuyamaca / Pathway / Woodside, Santee ──────────────────────
  3: [
    {
      key: "argee",
      name: "Argee Corporation",
      address: "9920 Cuyamaca St",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "compucraft",
      name: "Compucraft",
      address: "9930 Cuyamaca St",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "vmp_metal",
      name: "VMP Metal",
      address: "9940 Pathway St",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "altech_machining",
      name: "Altech Machining",
      address: "9950 Cuyamaca St",
      city: "Santee",
      zip: "92071",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "ricks_machine_santee",
      name: "Rick's Machine Shop",
      address: "9960 Woodside Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "pacific_plating",
      name: "Pacific Plating",
      address: "9970 Cuyamaca St",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "bans_auto",
      name: "Ban's Auto",
      address: "9980 Woodside Ave",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "cuyamaca_cluster",
      name: "Cuyamaca Industrial Cluster",
      address: "9900–10000 Cuyamaca St",
      city: "Santee",
      zip: "92071",
      notes: "Multi-tenant — leave stack at building directory",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 4 — Magnolia Ave Industrial, El Cajon ───────────────────────────
  4: [
    {
      key: "competitive_metals",
      name: "Competitive Metals",
      address: "1370 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      notes: "MUST STOP — metals distributor, high referral value",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "jiffy_machine",
      name: "Jiffy Machine",
      address: "1380 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "able_sandblasting",
      name: "Able Sandblasting",
      address: "1390 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "sd_powder_coatings",
      name: "SD Powder Coatings",
      address: "1400 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "hrp_sales",
      name: "HRP Sales",
      address: "1410 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "gregs_auto_elcajon",
      name: "Greg's Auto",
      address: "1420 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "elite_auto_elcajon",
      name: "Elite Auto",
      address: "1430 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "raymonds_auto_machine",
      name: "Raymond's Auto Machine",
      address: "1440 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "advance_auto_elcajon",
      name: "Advance Auto",
      address: "1450 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "fd_auto",
      name: "F&D Auto",
      address: "1460 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "industrial_buildings_magnolia",
      name: "Industrial Buildings Cluster",
      address: "1300–1500 N Magnolia Ave",
      city: "El Cajon",
      zip: "92020",
      notes: "Multi-tenant row — drop at each unit",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 5 — Raleigh / Vernon / Marshall, El Cajon ──────────────────────
  5: [
    {
      key: "american_machine_tool",
      name: "American Machine & Tool",
      address: "1250 Raleigh Ave",
      city: "El Cajon",
      zip: "92020",
      notes: "PRIME target — large CNC & manual shop",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "ametek_rotron",
      name: "Ametek Rotron",
      address: "1260 Vernon Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "vertechs",
      name: "VerTechs",
      address: "1270 Raleigh Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "white_cap_elcajon",
      name: "White Cap",
      address: "1280 Marshall Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "eagle_mfg",
      name: "Eagle Manufacturing",
      address: "1290 Vernon Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "ag_metalworks",
      name: "A&G Metalworks",
      address: "1300 Raleigh Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "premier_metal_processing",
      name: "Premier Metal Processing",
      address: "1310 Marshall Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "industrial_rubber",
      name: "Industrial Rubber",
      address: "1320 Vernon Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "california_sheet_metal",
      name: "California Sheet Metal",
      address: "1330 Raleigh Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 6 — Bradley / Greenfield / Pioneer, El Cajon ───────────────────
  6: [
    {
      key: "gkn_aerospace",
      name: "GKN Aerospace",
      address: "2100 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "precision_metal_products_elcajon",
      name: "Precision Metal Products",
      address: "2110 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "aj_metal_finishing",
      name: "A&J Metal Finishing",
      address: "2120 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "weldmac",
      name: "Weldmac Mfg",
      address: "2130 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "zenix_aerospace",
      name: "Zenix Aerospace",
      address: "2140 Pioneer Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "cardinal_precision",
      name: "Cardinal Precision",
      address: "2150 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "tedders_metal",
      name: "Tedders Metal",
      address: "2160 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "powder_1",
      name: "Powder 1",
      address: "2170 Pioneer Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "erkom_auto",
      name: "Erkom Auto",
      address: "2180 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "high_precision_grinding",
      name: "High Precision Grinding",
      address: "2190 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "bear_machining",
      name: "Bear Machining",
      address: "2200 Pioneer Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "moell_machine",
      name: "Moell Machine",
      address: "2210 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "acclaim_precision",
      name: "Acclaim Precision",
      address: "2220 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "pro_dynamic_cnc",
      name: "Pro Dynamic CNC",
      address: "2230 Pioneer Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "cnc_direct",
      name: "CNC Direct",
      address: "2240 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "precision_edge_mfg",
      name: "Precision Edge Mfg",
      address: "2250 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "top_notch_mfg",
      name: "Top Notch Mfg",
      address: "2260 Pioneer Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "countywide_metal",
      name: "Countywide Metal",
      address: "2270 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "direct_sheet_metal",
      name: "Direct Sheet Metal",
      address: "2280 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "frontline_performance",
      name: "FrontLine Performance",
      address: "2290 Pioneer Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "jerames_mfg",
      name: "Jerames Manufacturing",
      address: "2300 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "veridiam",
      name: "Veridiam",
      address: "2310 Greenfield Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "dave_whipple_sheet_metal",
      name: "Dave Whipple Sheet Metal",
      address: "2320 Pioneer Way",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "flash_tech_mfg",
      name: "Flash Tech Mfg",
      address: "2330 Bradley Ave",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 7 — Gillespie Field Aerospace, El Cajon ────────────────────────
  7: [
    {
      key: "neal_aviation",
      name: "Neal Aviation",
      address: "1780 Joe Crosson Dr",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "chem_tronics",
      name: "Chem-Tronics",
      address: "1800 Joe Crosson Dr",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "aerowind",
      name: "Aerowind",
      address: "1820 Joe Crosson Dr",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "ecp_powder_coating",
      name: "ECP Powder Coating",
      address: "1840 Joe Crosson Dr",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "infinity_aerospace",
      name: "INFINITY Aerospace",
      address: "1860 Joe Crosson Dr",
      city: "El Cajon",
      zip: "92020",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "polishing_proz",
      name: "Polishing Proz",
      address: "1880 Joe Crosson Dr",
      city: "El Cajon",
      zip: "92020",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 8 — Bond / Olde Hwy 80, El Cajon ───────────────────────────────
  8: [
    {
      key: "titan_steel_fabricators",
      name: "Titan Steel Fabricators",
      address: "1550 N Melrose Dr",
      city: "El Cajon",
      zip: "92021",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "socal_machine_elcajon",
      name: "Socal Machine",
      address: "1560 N Melrose Dr",
      city: "El Cajon",
      zip: "92021",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "swift_powder_coat",
      name: "Swift Powder Coat",
      address: "1570 N Melrose Dr",
      city: "El Cajon",
      zip: "92021",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "clothey_sons_gunsmithing",
      name: "Clothey & Sons Gunsmithing",
      address: "1580 Olde Hwy 80",
      city: "El Cajon",
      zip: "92021",
      isPriority: true,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "alacrity_mfg",
      name: "Alacrity Manufacturing",
      address: "1590 N Melrose Dr",
      city: "El Cajon",
      zip: "92021",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 9 — Lakeside ────────────────────────────────────────────────────
  9: [
    {
      key: "grc_performance",
      name: "GRC Performance",
      address: "9965 Vine St",
      city: "Lakeside",
      zip: "92040",
      isPriority: true,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "hi_performance_machine",
      name: "Hi Performance Machine",
      address: "9975 Vine St",
      city: "Lakeside",
      zip: "92040",
      isPriority: true,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "ricks_machine_lakeside",
      name: "Rick's Machine Shop",
      address: "9985 Maine Ave",
      city: "Lakeside",
      zip: "92040",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "maki_mfg",
      name: "Maki Manufacturing",
      address: "9995 Riverside Dr",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "sd_hydraulics",
      name: "SD Hydraulics",
      address: "10005 Maine Ave",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "coating_services_lakeside",
      name: "Coating Services",
      address: "10015 Winter Gardens Blvd",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "jg_mobile_welding",
      name: "JG Mobile Welding",
      address: "10025 Vine St",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "lakeside_muffler_welding",
      name: "Lakeside Muffler & Welding",
      address: "10035 Maine Ave",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "jnb_auto",
      name: "JNB Auto",
      address: "10045 Riverside Dr",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "lakeside_radiator",
      name: "Lakeside Radiator",
      address: "10055 Winter Gardens Blvd",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "equip_auto_systems",
      name: "Equip Auto Systems",
      address: "10065 Vine St",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "lakeside_auto_service",
      name: "Lakeside Auto Service",
      address: "10075 Maine Ave",
      city: "Lakeside",
      zip: "92040",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 10 — La Mesa ────────────────────────────────────────────────────
  10: [
    {
      key: "shop_floor_automations",
      name: "Shop Floor Automations",
      address: "7235 Navajo Rd",
      city: "La Mesa",
      zip: "91942",
      notes: "Referral partner — leave extra stack, introduce Jobline",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "wilde_built_tactical",
      name: "Wilde Built Tactical",
      address: "7245 Navajo Rd",
      city: "La Mesa",
      zip: "91942",
      isPriority: true,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "fine_firearms",
      name: "Fine Firearms",
      address: "5480 Baltimore Dr",
      city: "La Mesa",
      zip: "91942",
      isPriority: true,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "la_mesa_motor_clinic",
      name: "La Mesa Motor Clinic",
      address: "7255 University Ave",
      city: "La Mesa",
      zip: "91942",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "la_mesa_auto_alignment",
      name: "La Mesa Auto-N-Alignment",
      address: "7265 University Ave",
      city: "La Mesa",
      zip: "91942",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "jm_autoworx",
      name: "JM Autoworx",
      address: "7275 Navajo Rd",
      city: "La Mesa",
      zip: "91942",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "tune_craft",
      name: "Tune Craft",
      address: "7285 University Ave",
      city: "La Mesa",
      zip: "91942",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "smartech_auto",
      name: "SmarTech Auto",
      address: "7295 Navajo Rd",
      city: "La Mesa",
      zip: "91942",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "via_mercado_cluster",
      name: "Via Mercado Auto Cluster",
      address: "7300–7350 Via Mercado",
      city: "La Mesa",
      zip: "91942",
      notes: "Multiple auto shops on Via Mercado — do row",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "sd_guns_lamesa",
      name: "SD Guns",
      address: "7355 University Ave",
      city: "La Mesa",
      zip: "91942",
      isPriority: true,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 11 — Spring Valley / Rancho San Diego ───────────────────────────
  11: [
    {
      key: "green_flash_machine",
      name: "Green Flash Machine",
      address: "9420 Jamacha Blvd",
      city: "Spring Valley",
      zip: "91977",
      notes: "PRIME — active CNC shop, strong fit",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "mhd_mfg",
      name: "MHD Manufacturing",
      address: "9430 Jamacha Blvd",
      city: "Spring Valley",
      zip: "91977",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "ttn_machining",
      name: "TTN Machining",
      address: "9440 Jamacha Blvd",
      city: "Spring Valley",
      zip: "91977",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "performance_specialties",
      name: "Performance Specialties",
      address: "9450 Jamacha Blvd",
      city: "Spring Valley",
      zip: "91977",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "yamaguchi_auto",
      name: "Yamaguchi Auto",
      address: "9460 Jamacha Blvd",
      city: "Spring Valley",
      zip: "91977",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 12 — Poway Industrial Corridor ─────────────────────────────────
  12: [
    {
      key: "advanced_machining_tooling",
      name: "Advanced Machining & Tooling",
      address: "12275 Kerran St",
      city: "Poway",
      zip: "92064",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "darmark",
      name: "Darmark",
      address: "12285 Kerran St",
      city: "Poway",
      zip: "92064",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "dye_precision_cnc",
      name: "Dye Precision CNC",
      address: "12295 Poway Rd",
      city: "Poway",
      zip: "92064",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "franklins_industries",
      name: "Franklins Industries",
      address: "12305 Kerran St",
      city: "Poway",
      zip: "92064",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "micron_machine",
      name: "Micron Machine",
      address: "12315 Poway Rd",
      city: "Poway",
      zip: "92064",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "advanced_engineering_edm",
      name: "Advanced Engineering & EDM",
      address: "12325 Kerran St",
      city: "Poway",
      zip: "92064",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "general_atomics",
      name: "General Atomics",
      address: "3550 General Atomics Ct",
      city: "Poway",
      zip: "92121",
      notes: "Large defense/aerospace — drop at front security desk",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "bae_systems_poway",
      name: "BAE Systems",
      address: "3560 General Atomics Ct",
      city: "Poway",
      zip: "92121",
      notes: "Defense contractor — drop at lobby",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "visionworks_engineering",
      name: "Visionworks Engineering",
      address: "12335 Kerran St",
      city: "Poway",
      zip: "92064",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 13 — Miramar / Mira Mesa ───────────────────────────────────────
  13: [
    {
      key: "etogen_precision",
      name: "Etogen Precision",
      address: "9625 Black Mountain Rd",
      city: "San Diego",
      zip: "92126",
      notes: "PRIME — precision CNC, excellent fit",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "accurate_machine_miramar",
      name: "Accurate Machine",
      address: "9635 Candida St",
      city: "San Diego",
      zip: "92126",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "tandem_metal",
      name: "Tandem Metal",
      address: "9645 Candida St",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "dd_tech",
      name: "D&D Tech",
      address: "9655 Candida St",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "clint_precision",
      name: "Clint Precision",
      address: "9665 Black Mountain Rd",
      city: "San Diego",
      zip: "92126",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "vinatech_engineering",
      name: "Vinatech Engineering",
      address: "9675 Candida St",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "kinetic_cnc_miramar",
      name: "Kinetic CNC (Miramar)",
      address: "9685 Black Mountain Rd",
      city: "San Diego",
      zip: "92126",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "inno_tech",
      name: "Inno Tech",
      address: "9695 Candida St",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "electronic_metal_fab",
      name: "Electronic Metal Fab",
      address: "9705 Black Mountain Rd",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "lt_cnc",
      name: "LT CNC",
      address: "9715 Candida St",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "cnc_machining_services_miramar",
      name: "CNC Machining Services",
      address: "9725 Black Mountain Rd",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "sunny_cnc",
      name: "Sunny CNC",
      address: "9735 Candida St",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "jplusc_custom_fab",
      name: "JplusE Custom Fab",
      address: "9745 Black Mountain Rd",
      city: "San Diego",
      zip: "92126",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "boeing_sd",
      name: "Boeing San Diego",
      address: "9755 Miramar Rd",
      city: "San Diego",
      zip: "92126",
      notes: "Drop at lobby/visitor center, ask for workforce dev contact",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
    {
      key: "axillon_aerospace",
      name: "Axillon Aerospace",
      address: "9765 Miramar Rd",
      city: "San Diego",
      zip: "92126",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: true,
    },
  ],

  // ─── Zone 14 — Firearms / Gunsmiths Regional ─────────────────────────────
  // Z14 is a consolidated reference list of firearms stops pulled from home
  // zones (Z8, Z10, Z19). These are NOT separate stops — do not double-visit.
  // The field checklist for Z14 shows only Z14-specific businesses (if any).
  14: [
    {
      key: "z14_regional_note",
      name: "Firearms Regional Reference",
      address: "Various (see Z8, Z10, Z19 for location-specific stops)",
      city: "San Diego County",
      zip: "00000",
      notes:
        "Z14 consolidates firearms dealers across the county for reference. " +
        "Clothey & Sons (Z8), Wilde Built Tactical (Z10), Fine Firearms (Z10), SD Guns (Z10), " +
        "Coastal Ordnance (Z19), 2C Gunsmith (Z19), Socal Gun (Z19) are covered in their home zones.",
      isPriority: false,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 15 — Mission Gorge / Railroad, Santee North ────────────────────
  15: [
    {
      key: "jimco_racing",
      name: "Jimco Racing",
      address: "9775 Glenoaks Way",
      city: "Santee",
      zip: "92071",
      notes: "Premier off-road race fab — high value stop",
      isPriority: true,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "horsman_auto",
      name: "Horsman Auto",
      address: "9785 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "karoomis",
      name: "Karoomi's",
      address: "9795 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "sharpe_auto",
      name: "Sharpe Auto",
      address: "9805 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "stability_alignment",
      name: "Stability Alignment",
      address: "9815 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "import_auto_santee",
      name: "Import Auto",
      address: "9825 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "santee_foreign_car",
      name: "Santee Foreign Car",
      address: "9835 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "santee_auto_care",
      name: "Santee Auto Care",
      address: "9845 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "phil_thearles",
      name: "Phil Thearle's",
      address: "9855 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "lloyds_collision",
      name: "Lloyd's Collision",
      address: "9865 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "baja_auto_santee",
      name: "Baja Auto",
      address: "9875 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: true,
      isAerospace: false,
    },
    {
      key: "metrix_auto",
      name: "Metrix Auto",
      address: "9885 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "rm_auto_sports",
      name: "RM Auto Sports",
      address: "9895 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "rose_auto",
      name: "Rose Auto",
      address: "9905 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "star_a_autobody",
      name: "Star A Autobody",
      address: "9915 Mission Gorge Rd",
      city: "Santee",
      zip: "92071",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 16 — Lemon Grove ────────────────────────────────────────────────
  16: [
    {
      key: "lemon_grove_automotive",
      name: "Lemon Grove Automotive",
      address: "7230 Broadway",
      city: "Lemon Grove",
      zip: "91945",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 17 — National City Industrial Corridor ──────────────────────────
  17: [
    {
      key: "gv_industries",
      name: "G.V. Industries",
      address: "2020 E 8th St",
      city: "National City",
      zip: "91950",
      notes: "PRIME — active CNC, known excellent culture fit",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "megla_mfg",
      name: "Megla Manufacturing",
      address: "2030 E 8th St",
      city: "National City",
      zip: "91950",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "robotek",
      name: "Robotek",
      address: "2040 E 8th St",
      city: "National City",
      zip: "91950",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "ez_spring_stamping",
      name: "E-Z Spring & Stamping",
      address: "2050 E 8th St",
      city: "National City",
      zip: "91950",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "western_hose_gasket",
      name: "Western Hose & Gasket",
      address: "2060 E 8th St",
      city: "National City",
      zip: "91950",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "willys_electronic",
      name: "Willy's Electronic",
      address: "2070 E 8th St",
      city: "National City",
      zip: "91950",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "gary_mfg",
      name: "Gary Manufacturing",
      address: "2080 E 8th St",
      city: "National City",
      zip: "91950",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 18 — Chula Vista ────────────────────────────────────────────────
  18: [
    {
      key: "machinex",
      name: "Machinex",
      address: "880 Energy Way",
      city: "Chula Vista",
      zip: "91911",
      notes: "PRIME — full-service CNC, top of zone",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "jack_west_cnc",
      name: "Jack West CNC",
      address: "890 Energy Way",
      city: "Chula Vista",
      zip: "91911",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "advanced_machining_solutions",
      name: "Advanced Machining Solutions",
      address: "900 Energy Way",
      city: "Chula Vista",
      zip: "91911",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "miller_cnc",
      name: "Miller CNC",
      address: "910 Energy Way",
      city: "Chula Vista",
      zip: "91911",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "valley_industrial_specialties",
      name: "Valley Industrial Specialties",
      address: "920 Energy Way",
      city: "Chula Vista",
      zip: "91911",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "cnc_electronics_west",
      name: "CNC Electronics West",
      address: "930 Energy Way",
      city: "Chula Vista",
      zip: "91911",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 19 — Kearny Mesa / Convoy ──────────────────────────────────────
  19: [
    {
      key: "metal_master_kearny",
      name: "Metal Master",
      address: "6050 Convoy St",
      city: "San Diego",
      zip: "92111",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "rj_kates",
      name: "R J Kates",
      address: "6060 Convoy St",
      city: "San Diego",
      zip: "92111",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "jerrys_welding_ronson",
      name: "Jerry's Welding (Ronson Rd)",
      address: "3940 Ronson Rd",
      city: "San Diego",
      zip: "92111",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "draco_fab_worx",
      name: "Draco Fab Worx",
      address: "6070 Convoy St",
      city: "San Diego",
      zip: "92111",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "coastal_ordnance",
      name: "Coastal Ordnance",
      address: "4150 Convoy St",
      city: "San Diego",
      zip: "92111",
      isPriority: true,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "twosee_gunsmith",
      name: "2C / TwoSee Gunsmith",
      address: "6080 Convoy St",
      city: "San Diego",
      zip: "92111",
      isPriority: true,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "socal_gun",
      name: "Socal Gun",
      address: "6090 Convoy St",
      city: "San Diego",
      zip: "92111",
      isPriority: true,
      isFirearms: true,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 20 — Mid-City / South Park / Imperial Ave ──────────────────────
  20: [
    {
      key: "craftec_machine",
      name: "Craftec Machine",
      address: "3180 Imperial Ave",
      city: "San Diego",
      zip: "92102",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "westech_metal_fab",
      name: "Westech Metal Fab",
      address: "3190 Imperial Ave",
      city: "San Diego",
      zip: "92102",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "sams_welding",
      name: "Sam's Welding",
      address: "3200 Imperial Ave",
      city: "San Diego",
      zip: "92102",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "rise_up_industries",
      name: "Rise Up Industries CNC",
      address: "3210 Imperial Ave",
      city: "San Diego",
      zip: "92102",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 21 — Point Loma / Ocean Beach ──────────────────────────────────
  21: [
    {
      key: "jerrys_welding_grant",
      name: "Jerry's Welding & Machine",
      address: "3001 Grant St",
      city: "San Diego",
      zip: "92106",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],

  // ─── Zone 22 — Sorrento Valley / Mesa Rim ────────────────────────────────
  22: [
    {
      key: "qualified_machine_shop",
      name: "Qualified Machine Shop",
      address: "10060 Sorrento Valley Rd",
      city: "San Diego",
      zip: "92121",
      isPriority: true,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
    {
      key: "ja_fabrication",
      name: "JA Fabrication",
      address: "10070 Sorrento Valley Rd",
      city: "San Diego",
      zip: "92121",
      isPriority: false,
      isFirearms: false,
      isOffRoad: false,
      isAerospace: false,
    },
  ],
};

/** Flat list of all stops across all zones */
export const ALL_STOPS: (DropStop & { zoneNumber: number })[] = Object.entries(
  ZONE_STOPS,
).flatMap(([zn, stops]) =>
  stops.map(s => ({ ...s, zoneNumber: Number(zn) })),
);

/** All stops for a given zone number */
export function getStopsForZone(zoneNumber: number): DropStop[] {
  return ZONE_STOPS[zoneNumber] ?? [];
}

/** Total stop count (excluding Z14 reference entry) */
export const TOTAL_STOP_COUNT = ALL_STOPS.filter(
  s => s.zoneNumber !== 14 || s.key !== "z14_regional_note",
).length;
