import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useUserOrganization } from "@/hooks/useUserOrganization";
import { useActivityLog } from "@/hooks/useActivityLog";
import { Json } from "@/integrations/supabase/types";

export interface NCRReport {
  id: string;
  organization_id: string;
  queue_item_id: string;
  ncr_number: string;
  work_order_number: string;
  part_number: string | null;
  serial_or_lot: string;
  operation_number: string;
  defect_type: string;
  disposition: string;
  description: string;
  authorized_by: string | null;
  authorized_by_name: string | null;
  authorized_at: string | null;
  authorization_status: string;
  quantity_affected: number;
  rework_wo_id: string | null;
  quality_signoff: boolean | null;
  customer_approval: boolean | null;
  rejection_reason: string | null;
  metadata: Record<string, unknown>;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface NCRAuditEntry {
  id: string;
  organization_id: string;
  ncr_id: string;
  queue_item_id: string;
  action: string;
  performed_by: string;
  performed_by_name: string;
  old_values: Record<string, unknown> | null;
  new_values: Record<string, unknown> | null;
  reason: string | null;
  created_at: string;
}

export interface CreateNCRInput {
  queue_item_id: string;
  work_order_number: string;
  part_number?: string;
  serial_or_lot: string;
  operation_number: string;
  defect_type: string;
  disposition: string;
  description: string;
  quantity_affected: number;
}

export function useNCR(filters?: {
  queue_item_id?: string;
  authorization_status?: string;
  disposition?: string;
}) {
  const { user, profile } = useAuth();
  const { organization } = useUserOrganization();
  const { logActivity } = useActivityLog();
  const [ncrs, setNcrs] = useState<NCRReport[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchNCRs = useCallback(async () => {
    if (!user || !organization?.id) return;

    setLoading(true);
    setError(null);

    let query = supabase
      .from("ncr_reports")
      .select("*")
      .eq("organization_id", organization.id)
      .order("created_at", { ascending: false });

    if (filters?.queue_item_id) {
      query = query.eq("queue_item_id", filters.queue_item_id);
    }
    if (filters?.authorization_status) {
      query = query.eq("authorization_status", filters.authorization_status);
    }
    if (filters?.disposition) {
      query = query.eq("disposition", filters.disposition);
    }

    const { data, error: fetchError } = await query;

    if (fetchError) {
      setError(fetchError.message);
    } else {
      setNcrs((data as NCRReport[]) || []);
    }
    setLoading(false);
  }, [user, organization?.id, filters?.queue_item_id, filters?.authorization_status, filters?.disposition]);

  useEffect(() => {
    fetchNCRs();
  }, [fetchNCRs]);

  // Realtime subscription
  useEffect(() => {
    if (!user || !organization?.id) return;

    const channel = supabase
      .channel("ncr-changes")
      .on(
        "postgres_changes",
        { event: "*", schema: "public", table: "ncr_reports" },
        () => fetchNCRs(),
      )
      .subscribe();

    return () => { supabase.removeChannel(channel); };
  }, [user, organization?.id, fetchNCRs]);

  const createNCR = useCallback(
    async (input: CreateNCRInput) => {
      if (!user || !organization?.id) return { error: "Not authenticated" };

      const { error } = await supabase.from("ncr_reports").insert({
        organization_id: organization.id,
        queue_item_id: input.queue_item_id,
        ncr_number: "PLACEHOLDER", // auto-generated by trigger
        work_order_number: input.work_order_number,
        part_number: input.part_number || null,
        serial_or_lot: input.serial_or_lot,
        operation_number: input.operation_number,
        defect_type: input.defect_type,
        disposition: input.disposition,
        description: input.description,
        quantity_affected: input.quantity_affected,
        created_by: user.id,
      });

      if (error) return { error: error.message };

      await logActivity("ncr_created", `NCR created for WO ${input.work_order_number}: ${input.defect_type}`, {
        disposition: input.disposition,
        quantity_affected: input.quantity_affected,
      } as unknown as Record<string, unknown>);

      await fetchNCRs();
      return { error: null };
    },
    [user, organization, logActivity, fetchNCRs],
  );

  const approveNCR = useCallback(
    async (ncrId: string) => {
      if (!user) return { error: "Not authenticated" };

      const { error } = await supabase.rpc("apply_ncr_disposition", {
        _ncr_id: ncrId,
        _approver_id: user.id,
      });

      if (error) return { error: error.message };

      await logActivity("ncr_approved", `NCR approved`, { ncr_id: ncrId } as unknown as Record<string, unknown>);
      await fetchNCRs();
      return { error: null };
    },
    [user, logActivity, fetchNCRs],
  );

  const rejectNCR = useCallback(
    async (ncrId: string, reason: string) => {
      if (!user) return { error: "Not authenticated" };

      const { error } = await supabase.rpc("reject_ncr", {
        _ncr_id: ncrId,
        _rejector_id: user.id,
        _reason: reason,
      });

      if (error) return { error: error.message };

      await logActivity("ncr_rejected", `NCR rejected: ${reason}`, { ncr_id: ncrId } as unknown as Record<string, unknown>);
      await fetchNCRs();
      return { error: null };
    },
    [user, logActivity, fetchNCRs],
  );

  const fetchAuditLog = useCallback(
    async (ncrId: string) => {
      const { data, error } = await supabase
        .from("ncr_audit_log")
        .select("*")
        .eq("ncr_id", ncrId)
        .order("created_at", { ascending: true });

      if (error) return { data: null, error: error.message };
      return { data: data as NCRAuditEntry[], error: null };
    },
    [],
  );

  return {
    ncrs,
    loading,
    error,
    fetchNCRs,
    createNCR,
    approveNCR,
    rejectNCR,
    fetchAuditLog,
  };
}
