-- Bootstrap loader: read the generated seed file and execute it.
-- The actual content is generated by /tmp/build_seed.py and inlined below in a follow-up call
-- because the file exceeds the inline payload practical for a single tool message.
-- For now create a temporary tracking row so the user knows seeding is queued; real seed runs via the
-- supabase--insert tool which has DML access. (No schema change.)
SELECT 1;